import React, { useState } from 'react';
import { useRegistration } from '../hooks/useRegistration';
import CompanyInfoStep from './CompanyInfoStep';
import CompanyDetailsStep from './CompanyDetailsStep';
import RefereesStep from './RefereesStep';
import DocumentsStep from './DocumentsStep';
import PaymentStep from './PaymentStep';
import './RegistrationForm.css';
import { useNavigate } from 'react-router-dom';
import { 
  ArrowBack as ArrowBackIcon, 
  Close as CloseIcon,
  Business as BusinessIcon,
  CheckCircle as CheckCircleIcon,
  Info as InfoIcon,
  Error as ErrorIcon,
  Warning as WarningIcon
} from '@mui/icons-material';

const RegistrationForm = () => {
  const {
    user,
    currentStep,
    loading,
    alert,
    formData,
    fileNames,
    organizationId,
    paymentStep,
    businessNatureOptions,
    showAlert,
    handleInputChange,
    handleFileChange,
    submitRegistration,
    nextStep,
    prevStep,
    setAlert
  } = useRegistration();
  const navigate = useNavigate();

  // State for custom confirmation modal
  const [confirmModal, setConfirmModal] = useState({
    open: false,
    title: '',
    message: '',
    type: 'warning',
    confirmText: 'Yes, Cancel',
    cancelText: 'Go Back',
    onConfirm: null
  });

  const handleSubmitRegistration = async () => {
    console.log('🗄️ Submitting to table: organizations_registry');
    console.log('📁 Using storage bucket: organization-docs');
    console.log('📝 Registration number will be auto-generated by database (shared sequence with admin-created)');
    
    try {
      const id = await submitRegistration();
      if (id) {
        setAlert({ type: 'success', message: '✅ Registration submitted! Redirecting to payment...' });
        navigate('/payment', { 
          state: { 
            organizationId: id,
            fromRegistration: true 
          } 
        });
      }
    } catch (error) {
      console.error('❌ Registration submission error:', error);
      showAlert('error', error.message);
    }
  };

  const handleGoBack = () => {
    if (currentStep > 1) {
      prevStep();
    } else {
      navigate('/dashboard');
    }
  };

  // Show custom confirmation modal instead of window.confirm
  const handleCancelRegistration = () => {
    setConfirmModal({
      open: true,
      title: 'Cancel Registration',
      message: 'Are you sure you want to cancel the registration? All entered data will be lost.',
      type: 'warning',
      confirmText: 'Yes, Cancel',
      cancelText: 'Go Back',
      onConfirm: () => {
        navigate('/dashboard');
        setConfirmModal({ ...confirmModal, open: false });
      }
    });
  };

  const closeConfirmModal = () => {
    setConfirmModal({ ...confirmModal, open: false });
  };

  // Get alert icon
  const getAlertIcon = (type) => {
    switch(type) {
      case 'success': return <CheckCircleIcon />;
      case 'info': return <InfoIcon />;
      case 'error': return <ErrorIcon />;
      default: return <InfoIcon />;
    }
  };

  return (
    <div className="registration-container">
      {/* Header with Back and Cancel buttons - Professional Design */}
      <div className="registration-header">
        <div className="header-left">
          <button 
            className="btn-back" 
            onClick={handleGoBack}
            title={currentStep > 1 ? "Go to previous step" : "Go back to dashboard"}
          >
            <ArrowBackIcon className="btn-icon" />
            <span className="btn-text">{currentStep > 1 ? 'Back' : 'Dashboard'}</span>
          </button>
        </div>
        <div className="header-center">
          <div className="header-brand">
            <BusinessIcon className="brand-icon" />
            <span className="brand-text">KACCIMA</span>
          </div>
        </div>
        <div className="header-right">
          <button 
            className="btn-cancel" 
            onClick={handleCancelRegistration}
            title="Cancel registration"
          >
            <CloseIcon className="btn-icon" />
            <span className="btn-text">Cancel</span>
          </button>
        </div>
      </div>

      {alert && (
        <div className={`mui-alert mui-alert-${alert.type}`}>
          <span className="mui-alert-icon">
            {getAlertIcon(alert.type)}
          </span>
          <span className="mui-alert-message">{alert.message}</span>
          <button className="mui-alert-close" onClick={() => setAlert(null)}>
            <CloseIcon fontSize="small" />
          </button>
        </div>
      )}

      <div className="registration-header-content">
        <div className="registration-title-section">
          <h1 className="registration-title">Member Registration</h1>
          <p className="registration-subtitle">Join the Kano Chamber of Commerce, Industry, Mines and Agriculture</p>
        </div>
        
        <div className="registration-progress-section">
          <p className="registration-progress">
            Step {currentStep} of {paymentStep ? '5' : '4'}
            {paymentStep && <span className="payment-badge"> - Payment</span>}
          </p>
          <div className="progress-bar-container">
            <div 
              className="progress-bar" 
              style={{ 
                width: `${(currentStep / (paymentStep ? 5 : 4)) * 100}%` 
              }}
            />
          </div>
          <p className="registration-hint">
            <InfoIcon className="hint-icon" fontSize="small" />
            Registration number will be auto-generated (shared sequence with admin-created organizations)
          </p>
        </div>
      </div>
      
      <form className="registration-form">
        {currentStep === 1 && (
          <CompanyInfoStep
            formData={formData}
            handleInputChange={handleInputChange}
            businessNatureOptions={businessNatureOptions}
            onNext={nextStep}
          />
        )}

        {currentStep === 2 && (
          <CompanyDetailsStep
            formData={formData}
            handleInputChange={handleInputChange}
            onPrev={prevStep}
            onNext={nextStep}
          />
        )}

        {currentStep === 3 && (
          <RefereesStep
            formData={formData}
            handleInputChange={handleInputChange}
            onPrev={prevStep}
            onNext={nextStep}
          />
        )}

        {currentStep === 4 && !paymentStep && (
          <DocumentsStep
            formData={formData}
            handleInputChange={handleInputChange}
            handleFileChange={handleFileChange}
            fileNames={fileNames}
            onPrev={prevStep}
            onSubmit={handleSubmitRegistration}
            loading={loading}
          />
        )}

        {currentStep === 5 && paymentStep && (
          <PaymentStep
            organizationId={organizationId}
            user={user}
            showAlert={showAlert}
          />
        )}
      </form>

      {/* Custom Confirmation Modal */}
      {confirmModal.open && (
        <div className="confirmation-overlay" onClick={closeConfirmModal}>
          <div className="confirmation-modal" onClick={(e) => e.stopPropagation()}>
            <div className={`confirmation-header confirmation-${confirmModal.type}`}>
              <span className="confirmation-icon">
                {confirmModal.type === 'success' && '✅'}
                {confirmModal.type === 'error' && '❌'}
                {confirmModal.type === 'warning' && <WarningIcon />}
                {confirmModal.type === 'info' && 'ℹ️'}
              </span>
              <h3>{confirmModal.title}</h3>
              <button className="confirmation-close" onClick={closeConfirmModal}>
                ×
              </button>
            </div>
            <div className="confirmation-body">
              <p>{confirmModal.message}</p>
            </div>
            <div className="confirmation-footer">
              <button 
                className="confirmation-btn confirmation-btn-secondary"
                onClick={closeConfirmModal}
              >
                {confirmModal.cancelText}
              </button>
              <button 
                className="confirmation-btn confirmation-btn-danger"
                onClick={() => {
                  if (confirmModal.onConfirm) {
                    confirmModal.onConfirm();
                  }
                }}
              >
                {confirmModal.confirmText}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default RegistrationForm;